on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: 4.3.0
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install shiny
        run: install.packages(c("shiny", "rsconnect"), type = "binary")
      - name: shinyapps credentials
        run: Rscript -e "rsconnect::setAccountInfo(name='lucapl', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
      - name: Push to shiny.io
        run: Rscript -e "rsconnect::deployApp(appName = 'Weather-Report')"
