on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: install.packages(c("shiny", "rsconnect"), type = "binary")
      - name: shinyapps credentials
        run: Rscript -e "rsconnect::setAccountInfo(name='lucapl', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
      - name: Push to shiny.io
        run: Rscript -e "rsconnect::deployApp(appName = 'appname')"
